# Generated by Django 5.1.2 on 2024-10-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(max_length=12)),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('python developer', 'python developer'), ('java developer', 'java developer'), ('django developer', 'django developer')], max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
    ]
